---
# tasks file for proxmox
- name: get vmid
    shell: "pvesh get /cluster/nextid"
    register: next_id
- name: Provision kvm
  proxmox_kvm:
    api_user    : "{{ api_username }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    vmid        : "{{ next_id.stdout|int * 1 }}"
    name        : "{{ next_id.stdout}}"
    node        : "{{ node_name }}"
    ide         : "{{ cd_rom }}"
    net         : "{{ net_work }}"
    virtio      : "{{ hard_disk }}"
    cores       : "{{ cpu_cores }}"
    vcpus       : "{{ cpu_vcpus }}"
    update      : "{{ is_update }}"
    state       : "{{ state }}"
