---
# tasks file for proxmox
- name: Provision kvm
  proxmox_kvm:
    api_user    : "{{ api_username }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    vmid        : "{{ vm_id }}"
    node        : "{{ node_name }}"
    ide         : "{{ cd_rom }}"
    net         : "{{ net_work }}"
    virtio      : "{{ hard_disk }}"
    cores       : "{{ cpu_cores }}"
    vcpus       : "{{ cpu_vcpus }}"
    update      : "{{ is_update }}"
    state       : "{{ state }}"
